Algoritmo "enquanto2"
// Disciplina   : [ Lógica de Programação ]
// Professor   : Rafael Lima 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Antonio Vinicius de Andrade
// Data atual  : 18/11/2021
Var
// Seção de Declarações das variáveis 
x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 x<-1

enquanto  (x>=1) e (x<=10)  faca
  escreva(" Digite um número: ")
  leia(x)
fimenquanto

Fimalgoritmo

