Algoritmo "ATIVINFNOME"
// Disciplina   : [ Lógica de Programação ]
// Professor   : Rafael Lima 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Antonio Vinicius de Andrade
// Data atual  : 09/11/2021
Var
// Seção de Declarações das variáveis 
nome:caractere //declaração de variaveis do tipo texto

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo