Algoritmo "contadorde1ate10"
// Disciplina   : [ Lógica de Programação ]
// Professor   : Rafael Lima 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Antonio Vinicius de Andrade
// Data atual  : 23/11/2021
Var
// Seção de Declarações das variáveis 
x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
repita
      x<-x+1
      escreval(" Numero: ", x)

ate(x=10)


Fimalgoritmo

