Algoritmo "SOMA DOIS NÚMEROS"
// Disciplina   : [ Lógica de Programação ]
// Professor   : Rafael Lima 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : ANTONIO VINICIUS DE ANDRADE
// Data atual  : 04/11/2021
Var
// Seção de Declarações das variáveis 
n1, n2, D: inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Digite dois números")
leia (n1)
leia (n2)
d<-n1+n2
escreva ("A soma eh igual a", d)
Fimalgoritmo